### ISSUE TITLE
Add github link

### ISSUE THREAD

**Issue by Pat-Lafon** [reikdas/reikdas.github.io#1]
This website could/should have a link to your github account. Add one?

**Comment by reikdas** [comment]
I don't care about displaying my GitHub profile :p

**Comment by Pat-Lafon** [comment]
Consider reopening this issue, without a link to your github profile, some of your claimed contributions to LLVM-based projects are not substantiated since you just link to their project pages. A profile link would be sufficient for any interested viewers.
