### ISSUE TITLE
Photo does not show up well in mobile

### ISSUE THREAD

**Issue by Pat-Lafon** [reikdas/reikdas.github.io#2]
Your photo is stretched in certain cases(as title).

**Comment by reikdas** [comment]
The problem isn't mobile. The image gets skewed in Safari. Would appreciate a fix if you can.

**Comment by Pat-Lafon** [comment]
Unfortunately I don't have the time to dive into the differences in javascript/css rendering between browsers at the moment.

**Comment by reikdas** [comment]
Pls

**Comment by reikdas** [comment]
Fixed in f24fd79d085e5fc5229e2379b5ca9852bdbcd840
